### ISSUE TITLE
Dataset link is not available

### ISSUE THREAD

**Issue by ArgoHA** [e96031413/HUAWEI-Trash-Detection-YOLOv5#6]
Hi! Your doodle drive link doesn't seem to work. Could you update it please?
https://drive.google.com/file/d/1E6JtyAt_TRSrK47d9F6-OtC9rrKFXsDc/view?usp=sharing

**Comment by e96031413** [comment]
Hi, please use the following url to download the files:

link: https://pan.baidu.com/s/1lh1D1wvXUV3rjJOUpWsBlA ； password: znk3
